
-- Drop existing tables to rebuild with new schema
DROP TABLE IF EXISTS public.participants CASCADE;
DROP TABLE IF EXISTS public.games CASCADE;

-- Create games table with is_group_game flag
CREATE TABLE public.games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_group_game BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create individual_participants table (for solo games like Chess)
CREATE TABLE public.individual_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  faculty TEXT NOT NULL,
  semester INTEGER NOT NULL CHECK (semester >= 1 AND semester <= 8),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create teams table (for group games like Football)
CREATE TABLE public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  team_name TEXT NOT NULL,
  team_members JSONB NOT NULL DEFAULT '[]'::jsonb,
  captain_faculty TEXT NOT NULL,
  captain_semester INTEGER NOT NULL CHECK (captain_semester >= 1 AND captain_semester <= 8),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.individual_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- RLS policies for games (authenticated users only)
CREATE POLICY "Authenticated users can view games" ON public.games
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert games" ON public.games
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update games" ON public.games
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete games" ON public.games
  FOR DELETE TO authenticated USING (true);

-- RLS policies for individual_participants
CREATE POLICY "Authenticated users can view individual_participants" ON public.individual_participants
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert individual_participants" ON public.individual_participants
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update individual_participants" ON public.individual_participants
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete individual_participants" ON public.individual_participants
  FOR DELETE TO authenticated USING (true);

-- RLS policies for teams
CREATE POLICY "Authenticated users can view teams" ON public.teams
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert teams" ON public.teams
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update teams" ON public.teams
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete teams" ON public.teams
  FOR DELETE TO authenticated USING (true);

-- Enable real-time for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.games;
ALTER PUBLICATION supabase_realtime ADD TABLE public.individual_participants;
ALTER PUBLICATION supabase_realtime ADD TABLE public.teams;
